# Generated by Django 6.0 on 2025-12-30 09:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('router_link', models.SlugField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('text', 'Text/Article'), ('video', 'Video'), ('lab', 'Hands-on Lab'), ('quiz', 'Quiz')], default='text', max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('key_indicators', models.TextField(blank=True, default='')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=15)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['module', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='MitreTactic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitre_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'mitre_tactics',
                'ordering': ['mitre_id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order_index', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['path', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('campaign', 'Campaign'), ('certification', 'Certification')], default='standard', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paths',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(default='student', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitre_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_subtechnique', models.BooleanField(default=False)),
                ('parent_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='api.mitretechnique')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='api.mitretactic')),
            ],
            options={
                'db_table': 'mitre_techniques',
                'ordering': ['mitre_id'],
            },
        ),
        migrations.CreateModel(
            name='LessonTechniqueMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance', models.CharField(choices=[('primary', 'Primary Focus'), ('secondary', 'Secondary/Related'), ('mentioned', 'Mentioned')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_links', to='api.lesson')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='api.mitretechnique')),
            ],
            options={
                'db_table': 'lesson_technique_map',
                'unique_together': {('lesson', 'technique')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='techniques',
            field=models.ManyToManyField(related_name='lessons', through='api.LessonTechniqueMap', to='api.mitretechnique'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.module'),
        ),
        migrations.CreateModel(
            name='NavBotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_used', models.CharField(blank=True, default='', max_length=255)),
                ('query_term', models.CharField(blank=True, default='', max_length=255)),
                ('result_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nav_bot_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.path'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('path', 'order_index')},
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'indexes': [models.Index(fields=['token_hash'], name='refresh_tok_token_h_2fa7c6_idx'), models.Index(fields=['user', 'revoked'], name='refresh_tok_user_id_a7fb02_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='user_progre_user_id_6f8a8f_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
