# Generated by Django 6.0 on 2025-12-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="title",
            field=models.CharField(default="TEMP", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("path", "order_index")},
        ),
    ]
