# Generated by Django 5.1.6 on 2025-12-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'ordering': ['order_index', 'title']},
        ),
        migrations.AddField(
            model_name='path',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
