# Generated by Django 6.0 on 2025-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_module_title_alter_module_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="key_indicators",
            field=models.TextField(blank=True, null=True),
        ),
    ]
