# Generated by Django 5.1.6 on 2025-12-30 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillChainPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kill_chain_phases',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TacticPhaseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactics', to='api.killchainphase')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.mitretactic')),
            ],
            options={
                'db_table': 'tactic_phase_map',
                'unique_together': {('tactic', 'phase')},
            },
        ),
    ]
