# Generated by Django 5.1.6 on 2025-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='tier',
            field=models.CharField(default='street', max_length=50),
        ),
        migrations.AddField(
            model_name='path',
            name='total_duration_hours',
            field=models.IntegerField(default=0),
        ),
    ]
