# Generated by Django 5.1.6 on 2025-12-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_path_tier_path_total_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='path',
            name='total_duration_hours',
        ),
    ]
