# Generated by Django 5.1.6 on 2025-12-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tool_alter_lessontechniquemap_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
